# Generated by Django 6.0.1 on 2026-05-05 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 200 символов', max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='URL-friendly название (латинские буквы, цифры, дефисы)', max_length=200, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, help_text='Необязательное описание категории', null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Отображается ли категория на сайте', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'каталог',
                'verbose_name_plural': 'каталог',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.TextField(verbose_name='Отзыв')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=50, verbose_name='Промокод')),
                ('name', models.CharField(max_length=255, verbose_name='Название акции')),
                ('is_percent', models.BooleanField(default=True, verbose_name='В процентах')),
                ('amount', models.IntegerField(verbose_name='Размер скидки')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа')),
                ('period', models.TimeField(verbose_name='Период действия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тип расписания',
                'verbose_name_plural': 'Типы расписания',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тренировки')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('workout_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID тренировки')),
                ('scheduled_date', models.DateField(verbose_name='Запланированная дата')),
                ('status', models.IntegerField(default=0, verbose_name='Статус')),
                ('trainer_notes', models.TextField(blank=True, null=True, verbose_name='Заметки тренера')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(verbose_name='Дата покупки')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('visit_total', models.IntegerField(default=0, verbose_name='Общее кол-во посещений')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonements.stock', verbose_name='Акция')),
                ('sub_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abonements.subscriptiontype', verbose_name='Тип расписания')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='Пол')),
                ('role', models.IntegerField(default=1, verbose_name='Роль пользователя')),
                ('reviews', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonements.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('occupation_type', models.IntegerField(verbose_name='Тип занятия')),
                ('favourites', models.BooleanField(default=False, verbose_name='Избранное')),
                ('schedule_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abonements.subscriptiontype', verbose_name='Тип расписания')),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, to='abonements.user', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(verbose_name='Время входа')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Время выхода')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonements.subscription', verbose_name='Абонемент')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещение',
            },
        ),
    ]
