# Generated by Django 6.0.1 on 2026-05-07 12:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='trainers/')),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_type',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='sub_type',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reviews',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subscriptiontype',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='period',
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abonements.category'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='abonements/'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='period_days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
