# Generated by Django 6.0.5 on 2026-05-07 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonements', '0002_trainer_remove_schedule_schedule_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='subscriptiontype',
            options={'verbose_name': 'Абонемент', 'verbose_name_plural': 'Абонементы'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='has_group',
            field=models.BooleanField(default=False, verbose_name='Групповые занятия'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='has_gym',
            field=models.BooleanField(default=True, verbose_name='Тренажерный зал'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='has_pool',
            field=models.BooleanField(default=False, verbose_name='Бассейн'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='visits_count',
            field=models.IntegerField(default=0, verbose_name='Количество посещений'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='experience_years',
            field=models.IntegerField(default=1, verbose_name='Опыт (лет)'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonements.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='abonements/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название абонемента'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='period_days',
            field=models.IntegerField(verbose_name='Срок действия (дней)'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.ImageField(upload_to='trainers/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя тренера'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialty',
            field=models.CharField(max_length=100, verbose_name='Специализация'),
        ),
    ]
