# Generated by Django 6.0.5 on 2026-05-07 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonements', '0003_alter_category_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='subscriptiontype',
            options={'ordering': ['price'], 'verbose_name': 'Абонемент', 'verbose_name_plural': 'Абонементы'},
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome иконка, например: fa-dumbbell', max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='features',
            field=models.TextField(blank=True, help_text='Возможности через запятую'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='has_spa',
            field=models.BooleanField(default=False, verbose_name='СПА'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonements.category'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='has_group',
            field=models.BooleanField(default=False, verbose_name='Групповые'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='abonements/'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='period_days',
            field=models.IntegerField(verbose_name='Срок (дней)'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='visits_count',
            field=models.IntegerField(default=0, verbose_name='Посещений'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='experience_years',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.ImageField(upload_to='trainers/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialty',
            field=models.CharField(max_length=100),
        ),
    ]
